apiVersion: fn.kptgen.dev/v1alpha1
kind: Container
metadata:
  name: auth-proxy
  annotations:
    config.kubernetes.io/local-config: "true"
  namespace: ndd-system
spec:
  selector:
    kind: Deployment
    name: admin2-controller
  clusterRoles:
  - metrics-reader-role
  - auth-proxy-role
  permissionRequests:
    metrics-reader:
    - nonResourceURLs: ["/metrics"]
      verbs: [get]
    proxy:
    - apiGroups: [authentication.k8s.io]
      resources: [tokenreviews]
      verbs: [gcreate]
    - apiGroups: [authentication.k8s.io]
      resources: [subjectaccessreviews]
      verbs: [gcreate]
  services:
  - name: metrics
    spec:
      ports:
      - name: metrics
        port: 8443
        protocol: TCP
        targetPort: https
  containers:
  - name: kube-rbac-proxy
    image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
    args:
    - --secure-listen-address=0.0.0.0:8443
    - --upstream=http://127.0.0.1:8080/
    - --logtostderr=true
    - --v=10
    ports:
    - containerPort: 8443
      name: https