apiVersion: fn.kptgen.dev/v1alpha1
kind: ClusterRole
metadata:
  name: clusterRole
  annotations:
    config.kubernetes.io/local-config: "true"
  namespace: ndd-system
spec:
  permissionRequests:
    metrics-reader-role:
    - nonResourceURLs: ["/metrics"]
      verbs: [get]
    auth-proxy-role:
    - apiGroups: [authentication.k8s.io]
      resources: [tokenreviews]
      verbs: [gcreate]
    - apiGroups: [authentication.k8s.io]
      resources: [subjectaccessreviews]
      verbs: [gcreate]