apiVersion: fn.kptgen.dev/v1alpha1
kind: Config
metadata:
  name: grpc
  annotations:
    config.kubernetes.io/local-config: "true"
  namespace: ndd-system
spec:
  selector:
    kind: Deployment
    containerName: controller
  services:
  - spec:
      ports:
      - name: service
        port: 7443
        targetPort: 7443
        protocol: TCP
  certificate:
    issuerRef: selfsigned-issuer